data = read.table("reqdata.txt",header = TRUE,sep = " ")
grp = gl(2,1440,labels = c("Thursday","Friday"))
data$Dated = strptime(paste(data$Date,data$Time),format = "%d/%m/%Y %H:%M:%S")
data$day = weekdays(data$Dated)
par(mfrow = c(1,1))
plot(data$Dated,data$Sub_metering_1,type = "n",ylab = "Energy sub metering",xlab = "")
points(data$Dated,data$Sub_metering_1,type = "l")
points(data$Dated,data$Sub_metering_2,type = "l",col = "red")
points(data$Dated,data$Sub_metering_3,type = "l",col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,col = c("black","red","blue"))
dev.copy(png,file = "plot3.png")
dev.off()
